{% set name = "drawpyo" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drawpyo-{{ version }}.tar.gz
  sha256: a5e1ea04adde679a05457147930b85b5aa949634c40ac41e09f74d216b422b81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - toml >=0.10.2

test:
  imports:
    - drawpyo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MerrimanInd/drawpyo
  summary: A Python library for programmatically generating draw.io charts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
