{% set name = "drawpyo" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drawpyo-{{ version }}.tar.gz
  sha256: cc2f147d4c10832600019cb276b2445c3dd32a96fbabf2951dbf7155a1f7a956

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - toml >=0.10.2

test:
  imports:
    - drawpyo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MerrimanInd/drawpyo
  summary: A Python library for programmatically generating draw.io charts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
